name: Third workflow
on: 
  push:
  schedule:
    - cron: 24 3 * * *
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NAME: Shibil
    steps:
      - name: print env
        run: echo $NAME
    
